Added native section in the docs
marcingrzejszczak/observability-boot-blog-post pull request #3
Opened 2022-10-10 11:40 UTC by marcingrzejszczak

2022-10-10 14:04 UTC, Buzzardo requested changes

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +The Spring Boot AutoConfiguration for WebMvc Observability is not yet there - that's why we needed to set things up manually. For more information check this https://github.com/spring-projects/spring
Change to: 

The Spring Boot AutoConfiguration for WebMvc Observability is not yet ready. As a result, we need to set things up manually. For more information, see this https://github.com/spring-projects/spring-boot/issues/32538[issue].

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +For the Spring Boot Exemplars AutoConfiguration to work properly we need to wait for https://github.com/spring-projects/spring-boot/pull/32399[this PR] and https://github.com/spring-projects/spring-b
Add commas after "work properly" and "Until then"

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +To better understand how Spring Boot supports Native please read https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5[this excellent blog post]. We will reuse that knowledge to ru
Add a comma after "supports Native" and remove "will"

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +You should get a similar output to this one
Change to: 

You should get output similar to this:

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +You can check Grafana for metrics and traces. Read the limitations section below on why you won't find any pushed logs to Loki.
Turn "limitations section" into a link and remove "below" (which you won't need, thanks to the link).

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +You will not see logs being pushed to Loki just yet. For more information look into https://github.com/spring-projects/spring-boot/issues/25847[this issue].
Add a comma after "For more information"

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +On the client side we needed to provide the `reflect-config.js` configuration manually. For more information look into https://github.com/open-telemetry/opentelemetry-java/pull/4832[this PR].
Change to:

On the client side, we need to provide the `reflect-config.js` configuration manually. For more information, see https://github.com/open-telemetry/opentelemetry-java/pull/4832[this PR].

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +You were also able to observe your applications using native images via Spring Native.
Change to:

You could also able observe your applications by using native images with Spring Native.

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +This is an exciting time for us. We would again like to thank everyone who has already contributed and reported feedback, and we look forward to further feedback (don't hesitate to check out Spring B
Change to:

This is an exciting time for us. We would again like to thank everyone who has already contributed and reported feedback, and we look forward to further feedback! Check out Spring Boot's latest snapshots!

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +The Spring Boot AutoConfiguration for WebMvc Observability is not yet there - that's why we needed to set things up manually. For more information check this https://github.com/spring-projects/spring
Change to:

The Spring Boot AutoConfiguration for WebMvc Observability is not yet ready. As a result, we need to set things up manually. For more information, see this https://github.com/spring-projects/spring-boot/issues/32538%5Bissue%5D.

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +For the Spring Boot Exemplars AutoConfiguration to work properly we need to wait for https://github.com/spring-projects/spring-boot/pull/32399[this PR] and https://github.com/spring-projects/spring-b
Add commas after "work properly" and "Until then"

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +To better understand how Spring Boot supports Native please read https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5[this excellent blog post]. We will reuse that knowledge to ru
Add a comma after "supports Native" and remove "will"

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +See also https://www.graalvm.org/java/quickstart/[GraalVM Quickstart]
Add a period at the end.

2022-10-10 14:04 UTC, Buzzardo commented on BLOG.adoc
> +See also https://www.graalvm.org/java/quickstart/[GraalVM Quickstart]
Add a period at the end.

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +You should get a similar output to this one
Change to:

You should get output similar to this:

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +You can check Grafana for metrics and traces. Read the limitations section below on why you won't find any pushed logs to Loki.
Turn "limitations section" into a link and remove "below" (which you won't need, thanks to the link).

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +You will not see logs being pushed to Loki just yet. For more information look into https://github.com/spring-projects/spring-boot/issues/25847[this issue].
Add a comma after "For more information"

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +On the client side we needed to provide the `reflect-config.js` configuration manually. For more information look into https://github.com/open-telemetry/opentelemetry-java/pull/4832[this PR].
Change to:

On the client side, we need to provide the reflect-config.js configuration manually. For more information, see https://github.com/open-telemetry/opentelemetry-java/pull/4832%5Bthis PR].

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +You were also able to observe your applications using native images via Spring Native.
Change to:

You could also able observe your applications by using native images with Spring Native.

2022-10-10 14:04 UTC, Buzzardo commented on docs/src/main/asciidoc/BLOG.adoc
> +This is an exciting time for us. We would again like to thank everyone who has already contributed and reported feedback, and we look forward to further feedback (don't hesitate to check out Spring B
Change to:

This is an exciting time for us. We would again like to thank everyone who has already contributed and reported feedback, and we look forward to further feedback! Check out Spring Boot's latest snapshots!

2022-10-11 07:47 UTC, marcingrzejszczak commented
Done via https://github.com/marcingrzejszczak/observability-boot-blog-post/commit/f5319252c6d891024fa1d42c42b38a2283b8a40e

2022-10-11 07:47 UTC, closed without merging